name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-13

    steps:
    - name: Show environments
      run: |
        sw_vers
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v1
    - name: Switch Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_14.3.app"
    - name: Checkout submodules
      run: |
        git submodule update --init
    - name: Lint Swift
      run: |
        swiftlint
    - name: Collect Workflow Telemetry
      uses: AlexPerathoner/workflow-telemetry-action@v0.9
      with:
        metric_frequency_thousands_of_second: 100
    - name: Unit Test
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.3.app
      run: |
        xcodebuild test -project CotEditor.xcodeproj \
        -scheme CotEditor CODE_SIGNING_ALLOWED=NO
